from enum import Enum

class Writer_Task (Enum):
    SET_FLOWRATE_LAYER_0 = 1
    SET_FLOWRATE_OTHER_LAYERS = 2
    SET_BED_TEMPERATURE = 3
    SET_PRINT_SPEED = 4

    ADDITIONAL_INFORMATION = 5
    PAUSE_EACH_LAYER = 6
    RETRACT_SYRINGE = 7

class Parser_Task (Enum):
    CREATE_GCODE = 1
    FIND_INDEXES = 2

    IMPROVE_GCODE_AT_END = 3
    CREATE_FINAL_GCODE = 4